# Generated by Django 5.1.2 on 2024-11-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_address_client_company_client_password_projct_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projct',
            new_name='Project',
        ),
    ]
