# Generated by Django 5.1.2 on 2024-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_projct_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
    ]
