# Generated by Django 5.1.2 on 2024-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_payment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='payment',
            field=models.ManyToManyField(blank=True, to='home.payment'),
        ),
    ]
