# Generated by Django 5.1.2 on 2024-11-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_payment_project_project_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
            preserve_default=False,
        ),
    ]
