# Generated by Django 5.1.2 on 2024-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
    ]
