# Generated by Django 5.1.2 on 2024-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_client_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cid',
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
