# Generated by Django 5.1.2 on 2024-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_amount_payment_received_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], max_length=100)),
            ],
        ),
    ]
